/*
 * Copyright (C) 2023 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.android.internal.net.ipsec.ike.utils;

// TODO: b/278944233 This file is a copy of an autogenerated class (except the method body is
// removed) by building IKE library based on new IKE atoms defined in statsD. This file will be
// removed when those IKE atoms are merged to the code base.
/** Utility class for logging statistics events. */
public final class IkeMetricsInterface {
    // Constants for atom codes.

    /**
     * IkeSessionTerminated ike_session_terminated<br>
     * Usage: StatsLog.write(StatsLog.IKE_SESSION_TERMINATED, int ike_caller, int session_type, int
     * ike_state, int ike_error);<br>
     */
    public static final int IKE_SESSION_TERMINATED = 678;

    // Constants for enum values.

    // Values for IkeSessionTerminated.ike_caller
    public static final int IKE_SESSION_TERMINATED__IKE_CALLER__CALLER_UNKNOWN = 0;
    public static final int IKE_SESSION_TERMINATED__IKE_CALLER__CALLER_IWLAN = 1;
    public static final int IKE_SESSION_TERMINATED__IKE_CALLER__CALLER_VCN = 2;
    public static final int IKE_SESSION_TERMINATED__IKE_CALLER__CALLER_VPN = 3;

    // Values for IkeSessionTerminated.session_type
    public static final int IKE_SESSION_TERMINATED__SESSION_TYPE__SESSION_UNKNOWN = 0;
    public static final int IKE_SESSION_TERMINATED__SESSION_TYPE__SESSION_IKE = 1;
    public static final int IKE_SESSION_TERMINATED__SESSION_TYPE__SESSION_CHILD = 2;

    // Values for IkeSessionTerminated.ike_state
    public static final int IKE_SESSION_TERMINATED__IKE_STATE__STATE_UNKNOWN = 0;
    public static final int IKE_SESSION_TERMINATED__IKE_STATE__STATE_IKE_KILL = 1;
    public static final int IKE_SESSION_TERMINATED__IKE_STATE__STATE_IKE_INITIAL = 2;
    public static final int IKE_SESSION_TERMINATED__IKE_STATE__STATE_IKE_CREATE_LOCAL_IKE_INIT = 3;
    public static final int IKE_SESSION_TERMINATED__IKE_STATE__STATE_IKE_CREATE_LOCAL_IKE_AUTH = 4;
    public static final int
            IKE_SESSION_TERMINATED__IKE_STATE__STATE_IKE_CREATE_LOCAL_IKE_AUTH_IN_EAP = 5;
    public static final int
            IKE_SESSION_TERMINATED__IKE_STATE__STATE_IKE_CREATE_LOCAL_IKE_AUTH_POST_EAP = 6;
    public static final int IKE_SESSION_TERMINATED__IKE_STATE__STATE_IKE_IDLE = 7;
    public static final int IKE_SESSION_TERMINATED__IKE_STATE__STATE_IKE_CHILD_PROCEDURE_ONGOING =
            8;
    public static final int IKE_SESSION_TERMINATED__IKE_STATE__STATE_IKE_RECEIVING = 9;
    public static final int IKE_SESSION_TERMINATED__IKE_STATE__STATE_IKE_REKEY_LOCAL_CREATE = 10;
    public static final int
            IKE_SESSION_TERMINATED__IKE_STATE__STATE_IKE_SIMULTANEOUS_REKEY_LOCAL_CREATE = 11;
    public static final int
            IKE_SESSION_TERMINATED__IKE_STATE__STATE_IKE_SIMULTANEOUS_REKEY_LOCAL_DELETE_REMOTE_DELETE =
                    12;
    public static final int
            IKE_SESSION_TERMINATED__IKE_STATE__STATE_IKE_SIMULTANEOUS_REKEY_LOCAL_DELETE = 13;
    public static final int
            IKE_SESSION_TERMINATED__IKE_STATE__STATE_IKE_SIMULTANEOUS_REKEY_REMOTE_DELETE = 14;
    public static final int IKE_SESSION_TERMINATED__IKE_STATE__STATE_IKE_REKEY_LOCAL_DELETE = 15;
    public static final int IKE_SESSION_TERMINATED__IKE_STATE__STATE_IKE_REKEY_REMOTE_DELETE = 16;
    public static final int IKE_SESSION_TERMINATED__IKE_STATE__STATE_IKE_DELETE_LOCAL_DELETE = 17;
    public static final int IKE_SESSION_TERMINATED__IKE_STATE__STATE_IKE_DPD_LOCAL_INFO = 18;
    public static final int IKE_SESSION_TERMINATED__IKE_STATE__STATE_IKE_MOBIKE_LOCAL_INFO = 19;
    public static final int IKE_SESSION_TERMINATED__IKE_STATE__STATE_CHILD_KILL = 101;
    public static final int IKE_SESSION_TERMINATED__IKE_STATE__STATE_CHILD_INITIAL = 102;
    public static final int IKE_SESSION_TERMINATED__IKE_STATE__STATE_CHILD_CREATE_LOCAL_CREATE =
            103;
    public static final int IKE_SESSION_TERMINATED__IKE_STATE__STATE_CHILD_IDLE = 104;
    public static final int
            IKE_SESSION_TERMINATED__IKE_STATE__STATE_CHILD_IDLE_WITH_DEFERRED_REQUEST = 105;
    public static final int
            IKE_SESSION_TERMINATED__IKE_STATE__STATE_CHILD_CLOSE_AND_AWAIT_RESPONSE = 106;
    public static final int IKE_SESSION_TERMINATED__IKE_STATE__STATE_CHILD_DELETE_LOCAL_DELETE =
            107;
    public static final int IKE_SESSION_TERMINATED__IKE_STATE__STATE_CHILD_DELETE_REMOTE_DELETE =
            108;
    public static final int IKE_SESSION_TERMINATED__IKE_STATE__STATE_CHILD_REKEY_LOCAL_CREATE = 109;
    public static final int
            IKE_SESSION_TERMINATED__IKE_STATE__STATE_CHILD_MOBIKE_REKEY_LOCAL_CREATE = 110;
    public static final int IKE_SESSION_TERMINATED__IKE_STATE__STATE_CHILD_REKEY_REMOTE_CREATE =
            111;
    public static final int IKE_SESSION_TERMINATED__IKE_STATE__STATE_CHILD_REKEY_LOCAL_DELETE = 112;
    public static final int IKE_SESSION_TERMINATED__IKE_STATE__STATE_CHILD_REKEY_REMOTE_DELETE =
            113;

    // Values for IkeSessionTerminated.ike_error
    public static final int IKE_SESSION_TERMINATED__IKE_ERROR__ERROR_NONE = 0;
    public static final int IKE_SESSION_TERMINATED__IKE_ERROR__ERROR_PROTOCOL_SINGLE_PAIR_REQUIRED =
            16418;
    public static final int IKE_SESSION_TERMINATED__IKE_ERROR__ERROR_INTERNAL = 65536;
    public static final int IKE_SESSION_TERMINATED__IKE_ERROR__ERROR_NETWORK_LOST = 131072;
    public static final int IKE_SESSION_TERMINATED__IKE_ERROR__ERROR_IO_GENERAL = 196608;
    public static final int IKE_SESSION_TERMINATED__IKE_ERROR__ERROR_IO_TIMEOUT = 196609;
    public static final int IKE_SESSION_TERMINATED__IKE_ERROR__ERROR_IO_DNS_FAILURE = 196610;
    public static final int IKE_SESSION_TERMINATED__IKE_ERROR__ERROR_PROTOCOL_UNKNOWN = 262144;
    public static final int
            IKE_SESSION_TERMINATED__IKE_ERROR__ERROR_PROTOCOL_UNSUPPORTED_CRITICAL_PAYLOAD = 262145;
    public static final int IKE_SESSION_TERMINATED__IKE_ERROR__ERROR_PROTOCOL_INVALID_IKE_SPI =
            262148;
    public static final int
            IKE_SESSION_TERMINATED__IKE_ERROR__ERROR_PROTOCOL_INVALID_MAJOR_VERSION = 262149;
    public static final int IKE_SESSION_TERMINATED__IKE_ERROR__ERROR_PROTOCOL_INVALID_SYNTAX =
            262151;
    public static final int IKE_SESSION_TERMINATED__IKE_ERROR__ERROR_PROTOCOL_INVALID_MESSAGE_ID =
            262153;
    public static final int IKE_SESSION_TERMINATED__IKE_ERROR__ERROR_PROTOCOL_NO_PROPOSAL_CHOSEN =
            262158;
    public static final int IKE_SESSION_TERMINATED__IKE_ERROR__ERROR_PROTOCOL_INVALID_KE_PAYLOAD =
            262161;
    public static final int
            IKE_SESSION_TERMINATED__IKE_ERROR__ERROR_PROTOCOL_AUTHENTICATION_FAILED = 262168;
    public static final int IKE_SESSION_TERMINATED__IKE_ERROR__ERROR_PROTOCOL_NO_ADDITIONAL_SAS =
            262179;
    public static final int
            IKE_SESSION_TERMINATED__IKE_ERROR__ERROR_PROTOCOL_INTERNAL_ADDRESS_FAILURE = 262180;
    public static final int IKE_SESSION_TERMINATED__IKE_ERROR__ERROR_PROTOCOL_FAILED_CP_REQUIRED =
            262181;
    public static final int IKE_SESSION_TERMINATED__IKE_ERROR__ERROR_PROTOCOL_TS_UNACCEPTABLE =
            262182;
    public static final int IKE_SESSION_TERMINATED__IKE_ERROR__ERROR_PROTOCOL_INVALID_SELECTORS =
            262183;
    public static final int IKE_SESSION_TERMINATED__IKE_ERROR__ERROR_PROTOCOL_TEMPORARY_FAILURE =
            262187;
    public static final int IKE_SESSION_TERMINATED__IKE_ERROR__ERROR_PROTOCOL_CHILD_SA_NOT_FOUND =
            262188;
    public static final int IKE_SESSION_TERMINATED__IKE_ERROR__ERROR_UNKNOWN = 268435455;

    // Write methods
    public static void write(int code, int arg1, int arg2, int arg3, int arg4) {
        // TODO: b/278944233 This file is a copy of an autogenerated class (except the method body
        // is removed) by building IKE library based on new IKE atoms defined in statsD. This file
        // will be removed when those IKE atoms are merged to the code base. Currently this is a
        // no-op function.
    }
}
